"""docx_builder.py — Word (.docx) narrative equity brief.

A 2-3 page written report on a single stock — what the company does, a
performance overview, fundamentals, the Wall-Street analyst view, our DCF fair
value, a probabilistic forward outlook, and key risks — the kind of one-pager an
investor wants before buying. Reuses the data the Analysis page already computes,
so it's an on-demand export alongside the Excel and PowerPoint reports.

    from docx_builder import build_stock_docx
    buf = build_stock_docx(ticker, df, period_label, company_details=…, …)
    # buf is a BytesIO positioned at 0, ready for st.download_button
"""
import io
import os

import numpy as np

from data import SECTOR_ETF_MAP

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

try:
    from constants import get_risk_free_rate
except Exception:                       # pragma: no cover
    def get_risk_free_rate():
        return 0.04

# ── Brand palette ─────────────────────────────────────────────────────────────
NAVY  = RGBColor(0x0F, 0x17, 0x2A)
BLUE  = RGBColor(0x1D, 0x4E, 0xD8)
SLATE = RGBColor(0x47, 0x55, 0x69)
GREEN = RGBColor(0x15, 0x80, 0x3D)
RED   = RGBColor(0xB9, 0x1C, 0x1C)
MUTED = RGBColor(0x64, 0x74, 0x8B)

_ASSET_LOGO = os.path.join(os.path.dirname(__file__), "assets", "logo_full.png")

DISCLAIMER = (
    "This report is generated by QuantWizard for informational and educational "
    "purposes only. It is not investment advice, a recommendation, or an offer to "
    "buy or sell any security. Analyst ratings reflect third-party Wall-Street "
    "consensus, not QuantWizard's opinion. Figures are estimates derived from "
    "third-party data and models and may contain errors. Past performance does not "
    "guarantee future results. Do your own research and consult a licensed "
    "financial professional before making investment decisions."
)


# ── Formatters ────────────────────────────────────────────────────────────────
def _money(v, suffix=""):
    if v is None:
        return "N/A"
    try:
        a = abs(v)
    except TypeError:
        return "N/A"
    if a >= 1e12:
        return f"${v/1e12:,.2f}T{suffix}"
    if a >= 1e9:
        return f"${v/1e9:,.2f}B{suffix}"
    if a >= 1e6:
        return f"${v/1e6:,.1f}M{suffix}"
    return f"${v:,.2f}{suffix}"


def _pct(v, dp=1, sign=False):
    if v is None:
        return "N/A"
    return (f"{v:+.{dp}f}%" if sign else f"{v:.{dp}f}%")


def _num(v, dp=2, suffix=""):
    if v is None:
        return "N/A"
    return f"{v:,.{dp}f}{suffix}"


# ── Small doc helpers ─────────────────────────────────────────────────────────
def _heading(doc, text, size=13):
    p = doc.add_paragraph()
    pf = p.paragraph_format
    pf.space_before = Pt(12)
    pf.space_after = Pt(3)
    r = p.add_run(text)
    r.bold = True
    r.font.size = Pt(size)
    r.font.color.rgb = NAVY
    return p


def _para(doc, text, size=10.5, color=None, bold=False, italic=False, after=6):
    p = doc.add_paragraph()
    p.paragraph_format.space_after = Pt(after)
    r = p.add_run(text)
    r.font.size = Pt(size)
    r.bold = bold
    r.italic = italic
    if color is not None:
        r.font.color.rgb = color
    return p


def _bullet(doc, text, size=10.5):
    p = doc.add_paragraph(style="List Bullet")
    p.paragraph_format.space_after = Pt(2)
    r = p.add_run(text)
    r.font.size = Pt(size)
    return p


def _table(doc, headers, rows, widths=None):
    """Multi-column table with a ruled header row. Skips empty row sets."""
    rows = [r for r in rows if r]
    if not rows:
        return None
    t = doc.add_table(rows=len(rows) + 1, cols=len(headers))
    t.autofit = True
    for j, h in enumerate(headers):
        c = t.rows[0].cells[j]
        r = c.paragraphs[0].add_run(str(h))
        r.bold = True
        r.font.size = Pt(9)
        r.font.color.rgb = MUTED
    for i, row in enumerate(rows, start=1):
        for j, v in enumerate(row):
            c = t.rows[i].cells[j]
            r = c.paragraphs[0].add_run("—" if v is None else str(v))
            r.font.size = Pt(9.5)
            r.font.color.rgb = NAVY if j == 0 else SLATE
            if j == 0:
                r.bold = True
    return t


def _trailing_return(closes, days):
    """Simple return over the last `days` observations, or None if too short."""
    try:
        s = [float(x) for x in closes if x is not None and not np.isnan(float(x))]
        if len(s) <= days or not s[-1 - days]:
            return None
        return (s[-1] / s[-1 - days] - 1) * 100
    except Exception:
        return None


def _kv_table(doc, rows):
    """Two-column label/value table with light styling."""
    rows = [(l, v) for l, v in rows if v is not None]
    if not rows:
        return
    t = doc.add_table(rows=len(rows), cols=2)
    t.autofit = True
    for i, (label, value) in enumerate(rows):
        lc, vc = t.rows[i].cells
        lp = lc.paragraphs[0]
        lr = lp.add_run(label)
        lr.font.size = Pt(9.5)
        lr.font.color.rgb = MUTED
        vp = vc.paragraphs[0]
        vr = vp.add_run(str(value))
        vr.font.size = Pt(9.5)
        vr.bold = True
        vr.font.color.rgb = NAVY
    return t


# ── Price chart PNG ───────────────────────────────────────────────────────────
def _price_chart_png(df, ticker):
    try:
        d = df.tail(504)
        x = d["Date"] if "Date" in d.columns else d.index
        fig, ax = plt.subplots(figsize=(7.0, 2.7), dpi=150)
        ax.plot(x, d["Close"], color="#1d4ed8", lw=1.6, label="Price")
        for ma, c in (("MA50", "#8b5cf6"), ("MA200", "#f59e0b")):
            if ma in d.columns and d[ma].notna().any():
                ax.plot(x, d[ma], color=c, lw=1.0, label=ma)
        ax.set_title(f"{ticker} — Price (recent)", fontsize=10, color="#0f172a", loc="left")
        ax.legend(fontsize=7, frameon=False, loc="upper left")
        ax.grid(alpha=0.22)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.tick_params(labelsize=7, colors="#64748b")
        for lbl in ax.get_xticklabels():
            lbl.set_rotation(0)
        fig.tight_layout()
        buf = io.BytesIO()
        fig.savefig(buf, format="png")
        plt.close(fig)
        buf.seek(0)
        return buf
    except Exception:
        plt.close("all")
        return None


# ── Main builder ──────────────────────────────────────────────────────────────
def build_stock_docx(ticker, df, period_label, company_details=None,
                     mc_summary=None, news_list=None, summary_text="",
                     fundamentals=None, analyst_data=None, dcf=None,
                     sector_df=None, peer_df=None):
    """Return a BytesIO .docx equity brief for one stock."""
    cd = company_details or {}
    f = fundamentals or {}
    doc = Document()

    # Section numbers are counted, not written. Several sections below render
    # only when their data exists (no Monte Carlo, no peer set, no sector
    # benchmark), so hardcoded numbers left visible gaps — a brief that jumps
    # from 6 to 8 reads as though a page went missing.
    _n = [0]

    def _sec(title):
        _n[0] += 1
        return f"{_n[0]}.  {title}"

    # Base style
    normal = doc.styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(10.5)
    normal.font.color.rgb = RGBColor(0x1E, 0x29, 0x3B)

    # ── Header / title ────────────────────────────────────────────────────────
    if os.path.exists(_ASSET_LOGO):
        try:
            hp = doc.add_paragraph()
            hp.add_run().add_picture(_ASSET_LOGO, height=Inches(0.32))
        except Exception:
            pass

    name = cd.get("Name", ticker)
    title = doc.add_paragraph()
    title.paragraph_format.space_after = Pt(0)
    tr = title.add_run(f"{name} ({ticker})")
    tr.bold = True
    tr.font.size = Pt(20)
    tr.font.color.rgb = NAVY

    sub = doc.add_paragraph()
    sub.paragraph_format.space_after = Pt(2)
    from datetime import datetime as _dt
    sr = sub.add_run(f"Equity Research Brief  ·  {_dt.now():%B %d, %Y}")
    sr.font.size = Pt(10)
    sr.font.color.rgb = MUTED

    # ── Metrics from price data ───────────────────────────────────────────────
    latest = df.iloc[-1]
    first = df.iloc[0]
    close_last = float(latest["Close"])
    close_first = float(first["Close"])
    period_ret = (close_last / close_first - 1) * 100 if close_first else None

    dr = df["Daily_Return"].dropna() if "Daily_Return" in df.columns else None
    ann_vol = float(dr.std() * np.sqrt(252) * 100) if dr is not None and len(dr) else None
    ann_ret = float(dr.mean() * 252 * 100) if dr is not None and len(dr) else None
    rfr_pct = get_risk_free_rate() * 100
    sharpe = ((ann_ret - rfr_pct) / ann_vol) if (ann_ret is not None and ann_vol) else None
    try:
        max_dd = float((df["Close"] / df["Close"].cummax() - 1).min() * 100)
    except Exception:
        max_dd = None
    hi52 = latest.get("52W_High")
    lo52 = latest.get("52W_Low")
    rsi = latest.get("RSI14")
    ma50 = latest.get("MA50")
    ma200 = latest.get("MA200")

    # Price/return summary line
    _rc = GREEN if (period_ret or 0) >= 0 else RED
    pl = doc.add_paragraph()
    pl.paragraph_format.space_before = Pt(6)
    r1 = pl.add_run(f"${close_last:,.2f}   ")
    r1.bold = True
    r1.font.size = Pt(14)
    r1.font.color.rgb = NAVY
    r2 = pl.add_run(f"{_pct(period_ret, 1, sign=True)} over {period_label}")
    r2.font.size = Pt(11)
    r2.bold = True
    r2.font.color.rgb = _rc

    # ── 1. What the company does ──────────────────────────────────────────────
    # The business comes first. A reader who does not know what the company
    # sells cannot evaluate a single number that follows, so the description
    # leads and the reference facts sit underneath it rather than the reverse.
    _heading(doc, _sec("What the Company Does"))
    desc = cd.get("Description")
    if desc and str(desc) != "N/A":
        _para(doc, str(desc), size=10.5, after=6)
    else:
        _para(doc, f"{name} is listed on {cd.get('Exchange', 'a US exchange')} and is "
                   f"classified under {cd.get('Industry') or cd.get('Sector') or 'an unstated industry'}. "
                   "The data provider returned no business description for this ticker, so the "
                   "commercial detail below is limited to reference data — treat the qualitative "
                   "reading of this report accordingly.",
              size=10.5, color=SLATE, italic=True)
    _kv_table(doc, [
        ("Industry", cd.get("Industry") if cd.get("Industry") != "N/A" else None),
        ("Exchange", cd.get("Exchange")),
        ("Country", cd.get("Country")),
        ("Employees", f"{int(cd.get('Employees')):,}" if cd.get("Employees")
                      and str(cd.get("Employees")) != "N/A" else None),
        ("Market Cap", _money(cd.get("Market Cap"))),
        ("Website", cd.get("Website")),
    ])

    # ── 2. Performance overview ───────────────────────────────────────────────
    _heading(doc, _sec("Performance Overview"))
    perf_bits = []
    if period_ret is not None:
        perf_bits.append(f"Over the {period_label} window, {ticker} has returned "
                         f"{period_ret:+.1f}%.")
    if ann_vol is not None:
        perf_bits.append(f"Annualised volatility is {ann_vol:.0f}%")
        if sharpe is not None:
            perf_bits[-1] += f", for a Sharpe ratio of {sharpe:.2f}"
        perf_bits[-1] += "."
    if max_dd is not None:
        perf_bits.append(f"The largest peak-to-trough drawdown over the period was "
                         f"{max_dd:.0f}%.")
    if hi52 and lo52:
        perf_bits.append(f"Shares trade at ${close_last:,.2f} within a 52-week range of "
                         f"${float(lo52):,.2f} to ${float(hi52):,.2f}.")
    if ma50 and ma200:
        rel = ("above both its 50- and 200-day moving averages, a constructive trend"
               if close_last > float(ma50) and close_last > float(ma200)
               else "below its 50- and 200-day moving averages, a cautious trend"
               if close_last < float(ma50) and close_last < float(ma200)
               else "between its 50- and 200-day moving averages, a mixed trend")
        perf_bits.append(f"The price is currently {rel}.")
    if rsi is not None:
        state = ("overbought" if rsi >= 70 else "oversold" if rsi <= 30 else "neutral")
        perf_bits.append(f"The 14-day RSI is {float(rsi):.0f} ({state}).")
    _para(doc, " ".join(perf_bits) if perf_bits else "Performance metrics were unavailable.")

    chart = _price_chart_png(df, ticker)
    if chart is not None:
        try:
            doc.add_picture(chart, width=Inches(6.5))
        except Exception:
            pass

    # ── 3. Sector & momentum ──────────────────────────────────────────────────
    # A stock's move is only interesting relative to what its sector did. Showing
    # the two side by side over several windows separates company-specific
    # performance from a sector-wide tide, which a single-stock return cannot.
    _WINDOWS = [("1 month", 21), ("3 months", 63), ("6 months", 126), ("1 year", 252)]
    _sec_name = (cd.get("Sector") or "").strip()
    _sec_etf  = SECTOR_ETF_MAP.get(_sec_name)

    # Pick a benchmark that actually exists. `fetch_sector_data` keys on
    # SECTOR_ETF_MAP, but Polygon reports sector as an SIC description
    # ("Rubber & Plastics Footwear"), which almost never matches those
    # GICS-style keys — so the sector frame is usually None. Rather than drop
    # the section, fall back to the broad market, which df already carries, and
    # say which benchmark was used. A comparison against SPY is worth more than
    # no comparison, provided the label is honest about what it is.
    _bench_series, _bench_label, _bench_kind = None, None, None
    if sector_df is not None and not sector_df.empty and "Sector_ETF_Cumulative" in sector_df.columns:
        _bench_series = list(sector_df["Sector_ETF_Cumulative"])
        _bench_label  = _sec_etf or "Sector ETF"
        _bench_kind   = f"the {_sec_name} sector proxy" if _sec_name else "its sector ETF"
    else:
        for _bt in ("SPY", "QQQ"):
            _cum = f"{_bt}_Cumulative"
            if _cum in df.columns and df[_cum].notna().any():
                _bench_series, _bench_label = list(df[_cum]), _bt
                _bench_kind = "the broad market (no sector ETF matched this ticker)"
                break

    if _bench_series is not None:
        _heading(doc, _sec("Sector & Momentum"))
        _para(doc,
              f"Benchmarked against {_bench_label}, {_bench_kind}. "
              "Trailing returns are price-only and exclude dividends.",
              size=9.5, color=MUTED, after=4)
        _rows, _lead, _lag = [], 0, 0
        _sc = list(df["Close"])
        _kc = _bench_series
        for _lbl, _d in _WINDOWS:
            _s, _k = _trailing_return(_sc, _d), _trailing_return(_kc, _d)
            if _s is None and _k is None:
                continue
            _rel = (_s - _k) if (_s is not None and _k is not None) else None
            if _rel is not None:
                _lead += 1 if _rel > 0 else 0
                _lag  += 1 if _rel < 0 else 0
            _rows.append([_lbl, _pct(_s, 1, sign=True), _pct(_k, 1, sign=True),
                          _pct(_rel, 1, sign=True)])
        _table(doc, ["Window", ticker, _bench_label, "Relative"], _rows)
        if _lead or _lag:
            _b = _bench_label
            if _lead > _lag:
                _msg = (f"{ticker} has outpaced {_b} in {_lead} of the "
                        f"{_lead + _lag} windows measured, which points to a "
                        f"company-specific driver rather than a broad move.")
            elif _lag > _lead:
                _msg = (f"{ticker} has lagged {_b} in {_lag} of the "
                        f"{_lead + _lag} windows measured, so some of the weakness "
                        f"is company-specific rather than market-wide.")
            else:
                _msg = (f"{ticker} has tracked {_b} closely, so recent performance "
                        f"looks driven more by the market than by the company.")
            _para(doc, _msg, size=10.5, after=4)

    # ── 4. Competitive set ────────────────────────────────────────────────────
    if peer_df is not None and not peer_df.empty and "Ticker" in peer_df.columns:
        _heading(doc, _sec("Competitive Set"))
        _prows = []
        for _, _r in peer_df.iterrows():
            _mc = _r.get("Market Cap ($B)")
            _prows.append([
                _r.get("Ticker"),
                str(_r.get("Company", ""))[:38],
                f"${_mc:,.1f}B" if isinstance(_mc, (int, float)) else "—",
                "subject" if str(_r.get("Ticker")) == ticker else "peer",
            ])
        _table(doc, ["Ticker", "Company", "Market cap", "Role"], _prows)
        # Deliberately not a moat claim. This is the comparison set the analysis
        # used; naming it lets the reader challenge the choice, which they cannot
        # do if the peer group is invisible.
        _para(doc,
              "These are the comparison companies used elsewhere in this report. "
              "They are selected by industry classification and size, not by a "
              "judgement about who competes most directly — treat the set as a "
              "starting point and substitute your own if you disagree with it.",
              size=9.5, color=MUTED, after=4)

    # ── 5. Fundamentals ───────────────────────────────────────────────────────
    if f.get("ok"):
        _heading(doc, _sec("Fundamentals"))
        m = f.get("margins", {})
        ret = f.get("returns", {})
        val = f.get("valuation", {})
        gr = f.get("growth", {})
        q = f.get("quality", {})
        fcf = f.get("fcf", {})
        _kv_table(doc, [
            ("Gross / Operating / Net margin",
             f"{_pct(m.get('gross'))} / {_pct(m.get('operating'))} / {_pct(m.get('net'))}"),
            ("Return on equity / assets",
             f"{_pct(ret.get('roe'))} / {_pct(ret.get('roa'))}"),
            ("P/E  ·  P/S  ·  P/B",
             f"{_num(val.get('pe'))} · {_num(val.get('ps'))} · {_num(val.get('pb'))}"),
            ("Revenue CAGR", _pct(gr.get("revenue_cagr"))),
            ("Free cash flow", _money(fcf.get("fcf"))),
            ("FCF yield", _pct(fcf.get("fcf_yield"))),
            ("Piotroski F-Score (0-9)",
             None if q.get("f_score") is None else f"{q.get('f_score')}"),
            ("Altman Z zone", q.get("z_zone")),
        ])
        # Narrative
        fb = []
        if m.get("net") is not None:
            fb.append(f"{ticker} converts {m['net']:.0f}% of revenue into net profit")
            if ret.get("roe") is not None:
                fb.append(f"and earns a {ret['roe']:.0f}% return on equity")
            fb[-1] += "."
        if gr.get("revenue_cagr") is not None:
            fb.append(f"Revenue has compounded at {gr['revenue_cagr']:.0f}% a year over "
                      "the available history.")
        if q.get("f_score") is not None:
            fscore = q["f_score"]
            qual = ("strong" if fscore >= 7 else "middling" if fscore >= 4 else "weak")
            fb.append(f"Its Piotroski F-Score of {fscore}/9 points to {qual} financial "
                      "health.")
        if val.get("pe") is not None:
            fb.append(f"Shares trade at roughly {val['pe']:.0f}× trailing earnings.")
        if fb:
            _para(doc, " ".join(fb))

    # ── 4. Analyst outlook & fair value ───────────────────────────────────────
    _heading(doc, _sec("Valuation & Fair Value"))
    consensus = None
    try:
        from market_data import consensus_from_recommendation
        consensus = consensus_from_recommendation((analyst_data or {}).get("recommendation"))
    except Exception:
        consensus = None
    if consensus:
        _para(doc,
              f"Wall-Street analysts covering {ticker} rate it a consensus "
              f"“{consensus['verdict']}” across {consensus['total']} ratings "
              f"({consensus['strong_buy']} strong buy, {consensus['buy']} buy, "
              f"{consensus['hold']} hold, {consensus['sell']} sell, "
              f"{consensus['strong_sell']} strong sell). This reflects analysts' "
              f"consensus, not QuantWizard's own view.")
    else:
        _para(doc, f"Wall-Street rating data was not available for {ticker}.")

    # Earnings surprises
    earnings = (analyst_data or {}).get("earnings") or []
    if earnings:
        beats = sum(1 for e in earnings if (e.get("surprisePercent") or 0) > 0)
        _para(doc, f"Across the last {len(earnings)} reported quarters, {ticker} beat "
                   f"analyst EPS estimates {beats} time(s).", size=10)

    # DCF
    if dcf and dcf.get("ok") and dcf.get("fair_value") is not None:
        up = dcf.get("upside")
        up_txt = (f"{up*100:+.0f}% versus the current price of ${dcf.get('price', close_last):,.2f}"
                  if up is not None else "")
        _para(doc,
              f"QuantWizard's two-stage discounted-cash-flow model estimates a fair "
              f"value of ${dcf['fair_value']:,.2f} per share — {up_txt} "
              f"(assuming a {dcf.get('wacc', 0)*100:.0f}% discount rate and "
              f"{dcf.get('terminal_growth', 0)*100:.1f}% long-run growth). "
              f"A DCF is highly sensitive to its assumptions and is one input, not a "
              f"price target.")

    # ── 5. Forward outlook (Monte Carlo) ──────────────────────────────────────
    if mc_summary:
        _heading(doc, _sec("Forward Outlook"))
        _para(doc,
              f"A Monte Carlo simulation of thousands of price paths projects a median "
              f"outcome of {mc_summary.get('Median (P50)', 'N/A')}, with a bearish "
              f"(5th-percentile) case of {mc_summary.get('Bear Case (P5)', 'N/A')} and a "
              f"bullish (75th-percentile) case of {mc_summary.get('Bull Case (P75)', 'N/A')}. "
              f"The model estimates a {mc_summary.get('Prob. of Gain', 'N/A')} probability "
              f"of a positive return. These are probabilistic scenarios, not forecasts, "
              f"and assume the stock's recent volatility persists.")

    # ── 6. Key risks ──────────────────────────────────────────────────────────
    _heading(doc, _sec("Key Things to Know"))
    risks = []
    if ann_vol is not None and ann_vol >= 40:
        risks.append(f"High volatility — {ann_vol:.0f}% annualised means large swings in "
                     "both directions are normal for this stock.")
    if max_dd is not None and max_dd <= -30:
        risks.append(f"It has fallen as much as {abs(max_dd):.0f}% from a peak within the "
                     "period; sizeable drawdowns are part of its history.")
    val = f.get("valuation", {}) if f.get("ok") else {}
    if val.get("pe") is not None and val["pe"] >= 35:
        risks.append(f"A rich valuation ({val['pe']:.0f}× earnings) leaves less margin for "
                     "error if growth disappoints.")
    if dcf and dcf.get("ok") and dcf.get("upside") is not None and dcf["upside"] < -0.10:
        risks.append("Our DCF fair value sits below the current price, suggesting the "
                     "market may be pricing in optimistic growth.")
    if consensus and consensus["verdict"] in ("Sell", "Strong Sell"):
        risks.append("Analyst consensus currently leans bearish.")
    if rsi is not None and rsi >= 70:
        risks.append("The RSI is in overbought territory, which can precede a pullback.")
    if not risks:
        risks.append("No outsized risk flags were triggered by the quantitative screens, "
                     "but every equity carries market, business, and valuation risk.")
    for rtxt in risks:
        _bullet(doc, rtxt)

    # ── The bottom line ───────────────────────────────────────────────────────
    if summary_text:
        _heading(doc, "The Bottom Line")
        _para(doc, str(summary_text))

    # ── 9. Sources & assumptions ──────────────────────────────────────────────
    # The single biggest credibility gap in a generated report is a page of
    # confident numbers with no statement of where they came from or what was
    # assumed to produce them. A reader cannot challenge a fair value without the
    # discount rate behind it, and cannot judge a margin without knowing which
    # filing it was read from. Everything load-bearing gets named here.
    _heading(doc, _sec("Sources & Assumptions"))

    _src_rows = []
    try:
        _asof = df["Date"].iloc[-1]
        _asof = _asof.strftime("%d %b %Y") if hasattr(_asof, "strftime") else str(_asof)[:10]
    except Exception:
        _asof = None
    _src_rows.append(["Price & technicals", "Polygon.io", f"{period_label} window",
                      _asof or "latest close"])
    if f.get("ok"):
        _src_rows.append(["Financial statements", f.get("source") or "SEC EDGAR / Polygon",
                          "Annual filings", str(f.get("as_of") or "latest")])
    if analyst_data:
        _src_rows.append(["Analyst consensus", "Finnhub", "Third-party, not ours", "latest"])
    if news_list:
        _src_rows.append(["News", "Multi-source aggregation", f"{len(news_list)} items", "recent"])
    if sector_df is not None and not sector_df.empty:
        _src_rows.append(["Sector benchmark", "Polygon.io",
                          SECTOR_ETF_MAP.get((cd.get("Sector") or "").strip()) or "sector ETF",
                          _asof or "latest close"])
    _table(doc, ["Input", "Source", "Basis", "As of"], _src_rows)

    # Model assumptions, stated rather than implied.
    _asm = []
    _d = dcf if isinstance(dcf, dict) else {}
    if _d.get("ok"):
        _wb = _d.get("wacc_basis") or {}
        _asm.append(("Discount rate (WACC)", _pct((_d.get("wacc") or 0) * 100, 2)))
        if _wb.get("beta") is not None:
            _asm.append(("How the rate was set",
                         f"CAPM · beta {_wb['beta']:.2f} ({period_label} vs benchmark) · "
                         f"Rf {_pct((_wb.get('risk_free') or 0)*100, 2)} · "
                         f"ERP {_pct((_wb.get('erp') or 0)*100, 1)}"))
            _asm.append(("Cost of debt / tax rate",
                         f"{_pct((_wb.get('cost_of_debt') or 0)*100, 2)} assumed · "
                         f"{_pct((_wb.get('tax_rate') or 0)*100, 0)} statutory"))
        else:
            _asm.append(("How the rate was set",
                         "Default rate — no benchmark available, so no beta was estimated"))
        _asm.append(("Terminal growth", _pct((_d.get("terminal_growth") or 0) * 100, 2)))
        _asm.append(("Forecast horizon", f"{_d.get('years')} years" if _d.get("years") else None))
        _asm.append(("Base free cash flow", _money(_d.get("base_fcf"))))
    _asm.append(("Risk-free rate", _pct(rfr_pct, 2) + " (3-month T-bill, FRED)"))
    _kv_table(doc, _asm)

    _para(doc,
          "Two things worth knowing about the numbers above. The discount rate is "
          "the most load-bearing assumption in any fair value — on identical "
          "financials, a low-beta rate and a high-beta rate can imply opposite "
          "conclusions — so it is stated rather than buried. And the cost of debt "
          "and tax rate are assumptions, not figures read from a filing: the "
          "statement data available here carries no interest expense. Where a "
          "figure could not be sourced it is shown as N/A rather than estimated.",
          size=9.5, color=MUTED, after=4)

    # ── Disclaimer ────────────────────────────────────────────────────────────
    doc.add_paragraph()
    dp = doc.add_paragraph()
    dpr = dp.add_run(DISCLAIMER)
    dpr.font.size = Pt(7.5)
    dpr.italic = True
    dpr.font.color.rgb = MUTED

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf
