"""docx_builder.py — Word (.docx) narrative equity brief.

A 2-3 page written report on a single stock — what the company does, a
performance overview, fundamentals, the Wall-Street analyst view, our DCF fair
value, a probabilistic forward outlook, and key risks — the kind of one-pager an
investor wants before buying. Reuses the data the Analysis page already computes,
so it's an on-demand export alongside the Excel and PowerPoint reports.

    from docx_builder import build_stock_docx
    buf = build_stock_docx(ticker, df, period_label, company_details=…, …)
    # buf is a BytesIO positioned at 0, ready for st.download_button
"""
import io
import os

import numpy as np

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

try:
    from constants import get_risk_free_rate
except Exception:                       # pragma: no cover
    def get_risk_free_rate():
        return 0.04

# ── Brand palette ─────────────────────────────────────────────────────────────
NAVY  = RGBColor(0x0F, 0x17, 0x2A)
BLUE  = RGBColor(0x1D, 0x4E, 0xD8)
SLATE = RGBColor(0x47, 0x55, 0x69)
GREEN = RGBColor(0x15, 0x80, 0x3D)
RED   = RGBColor(0xB9, 0x1C, 0x1C)
MUTED = RGBColor(0x64, 0x74, 0x8B)

_ASSET_LOGO = os.path.join(os.path.dirname(__file__), "assets", "logo_full.png")

DISCLAIMER = (
    "This report is generated by QuantWizard for informational and educational "
    "purposes only. It is not investment advice, a recommendation, or an offer to "
    "buy or sell any security. Analyst ratings reflect third-party Wall-Street "
    "consensus, not QuantWizard's opinion. Figures are estimates derived from "
    "third-party data and models and may contain errors. Past performance does not "
    "guarantee future results. Do your own research and consult a licensed "
    "financial professional before making investment decisions."
)


# ── Formatters ────────────────────────────────────────────────────────────────
def _money(v, suffix=""):
    if v is None:
        return "N/A"
    try:
        a = abs(v)
    except TypeError:
        return "N/A"
    if a >= 1e12:
        return f"${v/1e12:,.2f}T{suffix}"
    if a >= 1e9:
        return f"${v/1e9:,.2f}B{suffix}"
    if a >= 1e6:
        return f"${v/1e6:,.1f}M{suffix}"
    return f"${v:,.2f}{suffix}"


def _pct(v, dp=1, sign=False):
    if v is None:
        return "N/A"
    return (f"{v:+.{dp}f}%" if sign else f"{v:.{dp}f}%")


def _num(v, dp=2, suffix=""):
    if v is None:
        return "N/A"
    return f"{v:,.{dp}f}{suffix}"


# ── Small doc helpers ─────────────────────────────────────────────────────────
def _heading(doc, text, size=13):
    p = doc.add_paragraph()
    pf = p.paragraph_format
    pf.space_before = Pt(12)
    pf.space_after = Pt(3)
    r = p.add_run(text)
    r.bold = True
    r.font.size = Pt(size)
    r.font.color.rgb = NAVY
    return p


def _para(doc, text, size=10.5, color=None, bold=False, italic=False, after=6):
    p = doc.add_paragraph()
    p.paragraph_format.space_after = Pt(after)
    r = p.add_run(text)
    r.font.size = Pt(size)
    r.bold = bold
    r.italic = italic
    if color is not None:
        r.font.color.rgb = color
    return p


def _bullet(doc, text, size=10.5):
    p = doc.add_paragraph(style="List Bullet")
    p.paragraph_format.space_after = Pt(2)
    r = p.add_run(text)
    r.font.size = Pt(size)
    return p


def _kv_table(doc, rows):
    """Two-column label/value table with light styling."""
    rows = [(l, v) for l, v in rows if v is not None]
    if not rows:
        return
    t = doc.add_table(rows=len(rows), cols=2)
    t.autofit = True
    for i, (label, value) in enumerate(rows):
        lc, vc = t.rows[i].cells
        lp = lc.paragraphs[0]
        lr = lp.add_run(label)
        lr.font.size = Pt(9.5)
        lr.font.color.rgb = MUTED
        vp = vc.paragraphs[0]
        vr = vp.add_run(str(value))
        vr.font.size = Pt(9.5)
        vr.bold = True
        vr.font.color.rgb = NAVY
    return t


# ── Price chart PNG ───────────────────────────────────────────────────────────
def _price_chart_png(df, ticker):
    try:
        d = df.tail(504)
        x = d["Date"] if "Date" in d.columns else d.index
        fig, ax = plt.subplots(figsize=(7.0, 2.7), dpi=150)
        ax.plot(x, d["Close"], color="#1d4ed8", lw=1.6, label="Price")
        for ma, c in (("MA50", "#8b5cf6"), ("MA200", "#f59e0b")):
            if ma in d.columns and d[ma].notna().any():
                ax.plot(x, d[ma], color=c, lw=1.0, label=ma)
        ax.set_title(f"{ticker} — Price (recent)", fontsize=10, color="#0f172a", loc="left")
        ax.legend(fontsize=7, frameon=False, loc="upper left")
        ax.grid(alpha=0.22)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.tick_params(labelsize=7, colors="#64748b")
        for lbl in ax.get_xticklabels():
            lbl.set_rotation(0)
        fig.tight_layout()
        buf = io.BytesIO()
        fig.savefig(buf, format="png")
        plt.close(fig)
        buf.seek(0)
        return buf
    except Exception:
        plt.close("all")
        return None


# ── Main builder ──────────────────────────────────────────────────────────────
def build_stock_docx(ticker, df, period_label, company_details=None,
                     mc_summary=None, news_list=None, summary_text="",
                     fundamentals=None, analyst_data=None, dcf=None):
    """Return a BytesIO .docx equity brief for one stock."""
    cd = company_details or {}
    f = fundamentals or {}
    doc = Document()

    # Base style
    normal = doc.styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(10.5)
    normal.font.color.rgb = RGBColor(0x1E, 0x29, 0x3B)

    # ── Header / title ────────────────────────────────────────────────────────
    if os.path.exists(_ASSET_LOGO):
        try:
            hp = doc.add_paragraph()
            hp.add_run().add_picture(_ASSET_LOGO, height=Inches(0.32))
        except Exception:
            pass

    name = cd.get("Name", ticker)
    title = doc.add_paragraph()
    title.paragraph_format.space_after = Pt(0)
    tr = title.add_run(f"{name} ({ticker})")
    tr.bold = True
    tr.font.size = Pt(20)
    tr.font.color.rgb = NAVY

    sub = doc.add_paragraph()
    sub.paragraph_format.space_after = Pt(2)
    from datetime import datetime as _dt
    sr = sub.add_run(f"Equity Research Brief  ·  {_dt.now():%B %d, %Y}")
    sr.font.size = Pt(10)
    sr.font.color.rgb = MUTED

    # ── Metrics from price data ───────────────────────────────────────────────
    latest = df.iloc[-1]
    first = df.iloc[0]
    close_last = float(latest["Close"])
    close_first = float(first["Close"])
    period_ret = (close_last / close_first - 1) * 100 if close_first else None

    dr = df["Daily_Return"].dropna() if "Daily_Return" in df.columns else None
    ann_vol = float(dr.std() * np.sqrt(252) * 100) if dr is not None and len(dr) else None
    ann_ret = float(dr.mean() * 252 * 100) if dr is not None and len(dr) else None
    rfr_pct = get_risk_free_rate() * 100
    sharpe = ((ann_ret - rfr_pct) / ann_vol) if (ann_ret is not None and ann_vol) else None
    try:
        max_dd = float((df["Close"] / df["Close"].cummax() - 1).min() * 100)
    except Exception:
        max_dd = None
    hi52 = latest.get("52W_High")
    lo52 = latest.get("52W_Low")
    rsi = latest.get("RSI14")
    ma50 = latest.get("MA50")
    ma200 = latest.get("MA200")

    # Price/return summary line
    _rc = GREEN if (period_ret or 0) >= 0 else RED
    pl = doc.add_paragraph()
    pl.paragraph_format.space_before = Pt(6)
    r1 = pl.add_run(f"${close_last:,.2f}   ")
    r1.bold = True
    r1.font.size = Pt(14)
    r1.font.color.rgb = NAVY
    r2 = pl.add_run(f"{_pct(period_ret, 1, sign=True)} over {period_label}")
    r2.font.size = Pt(11)
    r2.bold = True
    r2.font.color.rgb = _rc

    # ── 1. What the company does ──────────────────────────────────────────────
    _heading(doc, "1.  Company Overview")
    _kv_table(doc, [
        ("Sector", cd.get("Sector")),
        ("Exchange", cd.get("Exchange")),
        ("Country", cd.get("Country")),
        ("Employees", f"{int(cd.get('Employees')):,}" if cd.get("Employees") else None),
        ("Market Cap", _money(cd.get("Market Cap"))),
        ("Website", cd.get("Website")),
    ])
    desc = cd.get("Description")
    if desc:
        _para(doc, str(desc), size=10.5, after=4)
    else:
        _para(doc, f"{name} operates in the {cd.get('Sector', 'market')} sector. "
                   "A detailed business description was not available from the data provider.",
              size=10.5)

    # ── 2. Performance overview ───────────────────────────────────────────────
    _heading(doc, "2.  Performance Overview")
    perf_bits = []
    if period_ret is not None:
        perf_bits.append(f"Over the {period_label} window, {ticker} has returned "
                         f"{period_ret:+.1f}%.")
    if ann_vol is not None:
        perf_bits.append(f"Annualised volatility is {ann_vol:.0f}%")
        if sharpe is not None:
            perf_bits[-1] += f", for a Sharpe ratio of {sharpe:.2f}"
        perf_bits[-1] += "."
    if max_dd is not None:
        perf_bits.append(f"The largest peak-to-trough drawdown over the period was "
                         f"{max_dd:.0f}%.")
    if hi52 and lo52:
        perf_bits.append(f"Shares trade at ${close_last:,.2f} within a 52-week range of "
                         f"${float(lo52):,.2f} to ${float(hi52):,.2f}.")
    if ma50 and ma200:
        rel = ("above both its 50- and 200-day moving averages, a constructive trend"
               if close_last > float(ma50) and close_last > float(ma200)
               else "below its 50- and 200-day moving averages, a cautious trend"
               if close_last < float(ma50) and close_last < float(ma200)
               else "between its 50- and 200-day moving averages, a mixed trend")
        perf_bits.append(f"The price is currently {rel}.")
    if rsi is not None:
        state = ("overbought" if rsi >= 70 else "oversold" if rsi <= 30 else "neutral")
        perf_bits.append(f"The 14-day RSI is {float(rsi):.0f} ({state}).")
    _para(doc, " ".join(perf_bits) if perf_bits else "Performance metrics were unavailable.")

    chart = _price_chart_png(df, ticker)
    if chart is not None:
        try:
            doc.add_picture(chart, width=Inches(6.5))
        except Exception:
            pass

    # ── 3. Fundamentals ───────────────────────────────────────────────────────
    if f.get("ok"):
        _heading(doc, "3.  Fundamentals")
        m = f.get("margins", {})
        ret = f.get("returns", {})
        val = f.get("valuation", {})
        gr = f.get("growth", {})
        q = f.get("quality", {})
        fcf = f.get("fcf", {})
        _kv_table(doc, [
            ("Gross / Operating / Net margin",
             f"{_pct(m.get('gross'))} / {_pct(m.get('operating'))} / {_pct(m.get('net'))}"),
            ("Return on equity / assets",
             f"{_pct(ret.get('roe'))} / {_pct(ret.get('roa'))}"),
            ("P/E  ·  P/S  ·  P/B",
             f"{_num(val.get('pe'))} · {_num(val.get('ps'))} · {_num(val.get('pb'))}"),
            ("Revenue CAGR", _pct(gr.get("revenue_cagr"))),
            ("Free cash flow", _money(fcf.get("fcf"))),
            ("FCF yield", _pct(fcf.get("fcf_yield"))),
            ("Piotroski F-Score (0-9)",
             None if q.get("f_score") is None else f"{q.get('f_score')}"),
            ("Altman Z zone", q.get("z_zone")),
        ])
        # Narrative
        fb = []
        if m.get("net") is not None:
            fb.append(f"{ticker} converts {m['net']:.0f}% of revenue into net profit")
            if ret.get("roe") is not None:
                fb.append(f"and earns a {ret['roe']:.0f}% return on equity")
            fb[-1] += "."
        if gr.get("revenue_cagr") is not None:
            fb.append(f"Revenue has compounded at {gr['revenue_cagr']:.0f}% a year over "
                      "the available history.")
        if q.get("f_score") is not None:
            fscore = q["f_score"]
            qual = ("strong" if fscore >= 7 else "middling" if fscore >= 4 else "weak")
            fb.append(f"Its Piotroski F-Score of {fscore}/9 points to {qual} financial "
                      "health.")
        if val.get("pe") is not None:
            fb.append(f"Shares trade at roughly {val['pe']:.0f}× trailing earnings.")
        if fb:
            _para(doc, " ".join(fb))

    # ── 4. Analyst outlook & fair value ───────────────────────────────────────
    _heading(doc, "4.  Analyst Outlook & Fair Value")
    consensus = None
    try:
        from market_data import consensus_from_recommendation
        consensus = consensus_from_recommendation((analyst_data or {}).get("recommendation"))
    except Exception:
        consensus = None
    if consensus:
        _para(doc,
              f"Wall-Street analysts covering {ticker} rate it a consensus "
              f"“{consensus['verdict']}” across {consensus['total']} ratings "
              f"({consensus['strong_buy']} strong buy, {consensus['buy']} buy, "
              f"{consensus['hold']} hold, {consensus['sell']} sell, "
              f"{consensus['strong_sell']} strong sell). This reflects analysts' "
              f"consensus, not QuantWizard's own view.")
    else:
        _para(doc, f"Wall-Street rating data was not available for {ticker}.")

    # Earnings surprises
    earnings = (analyst_data or {}).get("earnings") or []
    if earnings:
        beats = sum(1 for e in earnings if (e.get("surprisePercent") or 0) > 0)
        _para(doc, f"Across the last {len(earnings)} reported quarters, {ticker} beat "
                   f"analyst EPS estimates {beats} time(s).", size=10)

    # DCF
    if dcf and dcf.get("ok") and dcf.get("fair_value") is not None:
        up = dcf.get("upside")
        up_txt = (f"{up*100:+.0f}% versus the current price of ${dcf.get('price', close_last):,.2f}"
                  if up is not None else "")
        _para(doc,
              f"QuantWizard's two-stage discounted-cash-flow model estimates a fair "
              f"value of ${dcf['fair_value']:,.2f} per share — {up_txt} "
              f"(assuming a {dcf.get('wacc', 0)*100:.0f}% discount rate and "
              f"{dcf.get('terminal_growth', 0)*100:.1f}% long-run growth). "
              f"A DCF is highly sensitive to its assumptions and is one input, not a "
              f"price target.")

    # ── 5. Forward outlook (Monte Carlo) ──────────────────────────────────────
    if mc_summary:
        _heading(doc, "5.  Forward Outlook")
        _para(doc,
              f"A Monte Carlo simulation of thousands of price paths projects a median "
              f"outcome of {mc_summary.get('Median (P50)', 'N/A')}, with a bearish "
              f"(5th-percentile) case of {mc_summary.get('Bear Case (P5)', 'N/A')} and a "
              f"bullish (75th-percentile) case of {mc_summary.get('Bull Case (P75)', 'N/A')}. "
              f"The model estimates a {mc_summary.get('Prob. of Gain', 'N/A')} probability "
              f"of a positive return. These are probabilistic scenarios, not forecasts, "
              f"and assume the stock's recent volatility persists.")

    # ── 6. Key risks ──────────────────────────────────────────────────────────
    _heading(doc, "6.  Key Things to Know")
    risks = []
    if ann_vol is not None and ann_vol >= 40:
        risks.append(f"High volatility — {ann_vol:.0f}% annualised means large swings in "
                     "both directions are normal for this stock.")
    if max_dd is not None and max_dd <= -30:
        risks.append(f"It has fallen as much as {abs(max_dd):.0f}% from a peak within the "
                     "period; sizeable drawdowns are part of its history.")
    val = f.get("valuation", {}) if f.get("ok") else {}
    if val.get("pe") is not None and val["pe"] >= 35:
        risks.append(f"A rich valuation ({val['pe']:.0f}× earnings) leaves less margin for "
                     "error if growth disappoints.")
    if dcf and dcf.get("ok") and dcf.get("upside") is not None and dcf["upside"] < -0.10:
        risks.append("Our DCF fair value sits below the current price, suggesting the "
                     "market may be pricing in optimistic growth.")
    if consensus and consensus["verdict"] in ("Sell", "Strong Sell"):
        risks.append("Analyst consensus currently leans bearish.")
    if rsi is not None and rsi >= 70:
        risks.append("The RSI is in overbought territory, which can precede a pullback.")
    if not risks:
        risks.append("No outsized risk flags were triggered by the quantitative screens, "
                     "but every equity carries market, business, and valuation risk.")
    for rtxt in risks:
        _bullet(doc, rtxt)

    # ── The bottom line ───────────────────────────────────────────────────────
    if summary_text:
        _heading(doc, "The Bottom Line")
        _para(doc, str(summary_text))

    # ── Disclaimer ────────────────────────────────────────────────────────────
    doc.add_paragraph()
    dp = doc.add_paragraph()
    dpr = dp.add_run(DISCLAIMER)
    dpr.font.size = Pt(7.5)
    dpr.italic = True
    dpr.font.color.rgb = MUTED

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf
