"""
entitlements.py — who may export a report, and how many they have left.

THE MODEL THIS IMPLEMENTS
-------------------------
Reports are the wedge, so they are the thing that gets gated. On-screen analysis
stays free and unmetered for everyone, signed in or not — it is the trust surface
and the reason anyone arrives. Taking a *file* away requires an account.

    anonymous     full analysis on screen, unlimited
    signed in     N report exports, any format
    paid          unlimited                       (not wired — see below)

WHY THE LIMIT IS 25 TODAY AND NOT 2
-----------------------------------
The eventual free tier is about two reports: enough to check the quality on a
ticker you care about plus one to compare, not enough to satisfy. It is set to 25
now because the number nobody has is *how many reports a real user actually
generates*, and that distribution — not a guess — should set the tier. Until
`report_generations` has data in it, a low limit would be a paywall tuned by
vibes. Everything else in this module is the shape it will keep; lowering
FREE_REPORT_LIMIT and implementing `has_unlimited` is the whole of turning it on.

Metering deliberately does NOT respect `DEV_MODE_FREE`. That flag unlocks paid
features so the free beta can use them; this gate exists to make people sign in
and to collect the usage data, both of which have to happen *during* the beta to
be worth anything. The limit is generous enough that no beta user will hit it.

WHAT IS COUNTED
---------------
A generation, not a download — the moment a file is actually built. Downloading
the same file twice is one report, because it is one report. Regenerating over a
different period is a new one, because it is.

Formats are not metered separately. Excel, PowerPoint and Word of the same
analysis are one product in three wrappers, and per-format quotas would only
teach people to switch format to get the same report again.
"""

from __future__ import annotations

import streamlit as st

# The free allowance for a signed-in user. See the module docstring before
# changing it: 25 is a measurement setting, ~2 is the product setting.
FREE_REPORT_LIMIT = 25

# Session cache, so a page with two export panels doesn't make two round trips
# on every rerun. Invalidated whenever we record a generation.
_COUNT_KEY = "_reports_used_cache"


def _cached_count(email: str) -> int:
    hit = st.session_state.get(_COUNT_KEY)
    if isinstance(hit, tuple) and hit[0] == email:
        return hit[1]
    try:
        from database import count_report_generations
        n = count_report_generations(email)
    except Exception:
        n = -1
    st.session_state[_COUNT_KEY] = (email, n)
    return n


def has_unlimited(email: str | None) -> bool:
    """Whether this user's exports are uncapped.

    False for everyone today. This is the single place a paid plan will be
    checked — when Stripe is turned on, look the subscription or credit pack up
    here and nothing else in the app needs to change.
    """
    return False


def reports_used(email: str | None) -> int:
    """Exports generated by this user. -1 when unknown (backend unreachable)."""
    if not email:
        return -1
    return _cached_count(email)


def reports_remaining(email: str | None) -> int | None:
    """How many free exports are left. None means uncapped."""
    if has_unlimited(email):
        return None
    used = reports_used(email)
    if used < 0:
        # Count unavailable. Allow the export rather than block a legitimate user
        # over an outage — the log is the source of truth and it will catch up.
        return None
    return max(0, FREE_REPORT_LIMIT - used)


def record(email: str | None, kind: str, subject: str = "") -> None:
    """Log a generated report and drop the cached count. Never raises."""
    if not email:
        return
    try:
        from database import record_report_generation
        record_report_generation(email, kind, subject)
    except Exception:
        pass
    st.session_state.pop(_COUNT_KEY, None)


# ── The gate ──────────────────────────────────────────────────────────────────

def _panel(title: str, body: str) -> None:
    st.markdown(f"""
    <div style="border:1px solid #e2e8f0;border-radius:10px;background:#f8fafc;
                padding:1.1rem 1.3rem;margin:0.4rem 0 0.8rem">
        <div style="font-weight:650;color:#0f172a;font-size:0.95rem;
                    margin-bottom:0.35rem">{title}</div>
        <div style="font-size:0.86rem;color:#475569;line-height:1.65">{body}</div>
    </div>""", unsafe_allow_html=True)


def require_export(key: str) -> tuple[bool, str | None]:
    """Gate a report export. Returns (allowed, email).

    `key` must be unique per call site — the sign-in button needs its own widget
    key, and the stock page renders this panel twice on one screen.

    When `[auth]` is absent from secrets there is no sign-in to require, so the
    export is allowed and simply not metered. That mirrors the terms gate and
    keeps a half-configured deployment usable rather than bricked.
    """
    import auth

    if not auth.auth_configured():
        return True, None

    if not auth.is_signed_in():
        _panel("Sign in to download this report",
               "The analysis on screen is free and always will be. Exporting it "
               "as an Excel workbook, a PowerPoint deck or a Word document needs "
               "an account — it takes a moment and we never see your password.")
        if st.button("Sign in", type="primary", key=f"exp_signin_{key}"):
            auth.sign_in()
        return False, None

    email = auth.current_email()
    left  = reports_remaining(email)

    if left is not None and left <= 0:
        _panel("You've used your free reports",
               f"That's {FREE_REPORT_LIMIT} exports on this account. The full "
               "analysis stays free on screen — it's the downloadable files that "
               "are capped. More options are coming shortly; in the meantime "
               "reply to any email from us and we'll sort you out.")
        return False, email

    return True, email


def render_quota_note(email: str | None) -> None:
    """A quiet line showing what's left. Silent when uncapped or unknown."""
    left = reports_remaining(email)
    if left is None:
        return
    word = "report" if left == 1 else "reports"
    st.markdown(
        f'<div style="font-size:0.75rem;color:#94a3b8;margin:0.15rem 0 0.5rem">'
        f'{left} free {word} remaining</div>', unsafe_allow_html=True)
