"""portfolio_narrative.py — the written analysis behind the portfolio reports.

Turns a tracked portfolio's holdings, weights, sector mix, risk metrics and
realised performance into the prose an analyst would write about it: what the
portfolio is, what drove the result, what it is exposed to, and what a reviewer
would raise.

Every sentence is DERIVED from a computed number. Nothing is generated by a
language model, and that is deliberate: this text ends up in a document a user
may act on, and a fluent sentence containing an invented figure is worse than
no sentence at all. The cost of that choice is that the phrasing comes from a
finite set of templates; the benefit is that a claim can always be traced to
the metric that produced it, and the numbers inside a sentence are the same
numbers in the tables beside it.

Shared by the Word report and the PowerPoint deck so the two never disagree.

    from portfolio_excel import _derive_portfolio_stats
    from portfolio_narrative import build_narrative
    stats = _derive_portfolio_stats(tracked, profiles)
    n = build_narrative(name, tracked, stats)
"""

from __future__ import annotations

# Sectors that historically cushion drawdowns vs those that amplify the cycle.
# yfinance's sector vocabulary, plus the labels our own profile fetch emits.
DEFENSIVE_SECTORS = {
    "Utilities", "Consumer Defensive", "Consumer Staples", "Healthcare",
    "Health Care", "Real Estate",
}
CYCLICAL_SECTORS = {
    "Technology", "Consumer Cyclical", "Consumer Discretionary",
    "Financial Services", "Financials", "Energy", "Industrials",
    "Basic Materials", "Materials", "Communication Services",
}

# A single position above this is worth naming as concentration in prose.
CONCENTRATION_POSITION = 0.20
# Sector weight above this gets called out. 30% is the conventional line.
CONCENTRATION_SECTOR = 0.30


def _pct(v, dp=1, sign=False):
    if v is None:
        return "n/a"
    return f"{v:+.{dp}f}%" if sign else f"{v:.{dp}f}%"


def _f(v):
    """Weight (a fraction) as a percentage string."""
    return "n/a" if v is None else f"{v:.1%}"


def _sector_weights(stats):
    """{sector: weight fraction}, largest first."""
    tot = stats.get("total_value") or 0
    if not tot:
        return []
    return [(s, v / tot) for s, v in stats.get("sectors", [])]


def _defensive_share(stats):
    """Fraction of the book in defensive sectors, and in cyclicals."""
    d = c = 0.0
    for sec, w in _sector_weights(stats):
        if sec in DEFENSIVE_SECTORS:
            d += w
        elif sec in CYCLICAL_SECTORS:
            c += w
    return d, c


def _contributions(stats):
    """Per-holding dollar gain and share of the portfolio's total gain.

    Contribution is measured in DOLLARS against cost basis, not as a return:
    a 60% gain on a 1% position moved the portfolio far less than a 6% gain on
    a 30% one, and ranking by percentage return says the opposite.
    """
    out = []
    for r in stats.get("rows", []):
        cost = r.get("cost_basis")
        if not cost:
            continue
        out.append({
            "ticker": r["ticker"], "name": r.get("name") or r["ticker"],
            "gain_usd": r["value"] - cost, "gain_pct": r.get("gain_pct"),
            "weight": r.get("w"),
        })
    out.sort(key=lambda x: -(x["gain_usd"] or 0))
    return out


def _style_tilt(stats):
    """(label, sentence) describing growth vs value character."""
    pe, g = stats.get("wpe"), stats.get("rev_growth")
    dy = stats.get("div_yield") or 0
    if pe is None and g is None:
        return "Unclassified", ("Too few holdings report earnings and growth data "
                                "to characterise the portfolio's style.")
    rich = pe is not None and pe > 25
    cheap = pe is not None and pe < 15
    fast = g is not None and g > 0.12
    slow = g is not None and g < 0.04

    if rich and fast:
        return "Growth", (
            f"The portfolio carries a clear growth tilt: a weighted P/E of "
            f"{pe:.1f}x alongside revenue growth of {_f(g)} means holders are "
            f"paying up for expansion rather than for current earnings.")
    if cheap and not fast:
        return "Value", (
            f"The portfolio reads as value-oriented — a weighted P/E of {pe:.1f}x "
            f"with revenue growth of {_f(g) if g is not None else 'n/a'} indicates "
            f"holdings priced on what they earn today rather than on what they "
            f"might earn later.")
    if dy > 0.03 and slow:
        return "Income", (
            f"With a {_f(dy)} dividend yield against modest revenue growth, this "
            f"is an income-oriented book: the return case rests more on cash "
            f"distributions than on earnings expansion.")
    detail = []
    if pe is not None:
        detail.append(f"a weighted P/E of {pe:.1f}x")
    if g is not None:
        detail.append(f"revenue growth of {_f(g)}")
    tail = (" and ".join(detail) + " sit close to broad-market norms"
            if detail else "its fundamentals are mixed across holdings")
    return "Blend", (f"The portfolio sits between growth and value — {tail}, "
                     f"so style is not the main driver of its behaviour.")


def _posture(stats):
    """(label, sentence) on defensive vs aggressive positioning."""
    beta = stats.get("beta")
    dshare, cshare = _defensive_share(stats)
    if beta is None:
        return "Unclassified", ("Not enough holdings publish a beta to place the "
                                "portfolio on the defensive-to-aggressive scale.")
    if beta > 1.15:
        lbl = "Aggressive"
        s = (f"A weighted beta of {beta:.2f} puts the portfolio ahead of the market "
             f"in both directions — it should be expected to gain more than the "
             f"S&P 500 in rallies and lose more in selloffs.")
    elif beta < 0.85:
        lbl = "Defensive"
        s = (f"A weighted beta of {beta:.2f} means the portfolio is built to move "
             f"less than the market, giving up some upside in exchange for a "
             f"shallower path through declines.")
    else:
        lbl = "Market-like"
        s = (f"A weighted beta of {beta:.2f} places the portfolio close to the "
             f"market's own risk: it should broadly track the S&P 500 rather than "
             f"lead or lag it structurally.")
    if dshare > 0.35:
        s += (f" {_f(dshare)} of assets sit in traditionally defensive sectors, "
              f"which reinforces that positioning.")
    elif cshare > 0.70:
        s += (f" {_f(cshare)} of assets sit in cyclical sectors, so the portfolio's "
              f"fortunes are closely tied to the economic cycle.")
    return lbl, s


def _objective(stats):
    """One line describing what this portfolio appears built to do."""
    style, _ = _style_tilt(stats)
    posture, _ = _posture(stats)
    n = stats.get("n", 0)
    dy = stats.get("div_yield") or 0
    bits = []
    if style in ("Growth", "Value", "Income", "Blend"):
        bits.append(f"{style.lower()}-oriented")
    bits.append(f"{posture.lower()} risk profile")
    # "A 8-position" — the article depends on how the number is spoken, and
    # 8, 11 and 18 all start with a vowel sound.
    art = "An" if str(n)[0] in "８8" or str(n).startswith(("8", "11", "18")) else "A"
    obj = (f"{art} {n}-position, " + ", ".join(bits) + " equity portfolio")
    if dy > 0.025:
        obj += f", generating a {_f(dy)} dividend yield"
    return obj + "."


def _assessment(stats, m):
    """Overall verdict paragraph — performance, risk and structure in one place."""
    tr = m.get("Total Return")
    alpha = m.get("vs S&P 500")
    eff = stats.get("eff_n")
    parts = []
    if tr is not None:
        parts.append(f"The portfolio has returned {_pct(tr, sign=True)} on invested "
                     f"capital since inception")
        if isinstance(alpha, (int, float)):
            verb = "ahead of" if alpha >= 0 else "behind"
            parts[-1] += (f", {abs(alpha):.1f} points {verb} an S&P 500 position "
                          f"funded on the same schedule")
        parts[-1] += "."
    if eff:
        parts.append(f"Its {stats['n']} holdings behave like roughly {eff:.0f} "
                     f"equally-sized ones once weights are accounted for")
        if stats["hhi"] > 0.18:
            parts[-1] += ", so results are driven by a handful of names."
        else:
            parts[-1] += ", a reasonably even spread."
    lg = stats.get("largest")
    if lg and lg["w"] > CONCENTRATION_POSITION:
        parts.append(f"{lg['ticker']} alone accounts for {_f(lg['w'])} of assets, "
                     f"which makes the portfolio's path materially dependent on "
                     f"one company.")
    return " ".join(parts) if parts else "Insufficient history for an assessment."


def _strengths(stats, m):
    out = []
    thin = stats.get("thin_history")
    hhi, n, eff = stats["hhi"], stats["n"], stats.get("eff_n")
    if hhi < 0.12 and n >= 10:
        out.append(f"Genuine diversification — {n} positions with an effective count "
                   f"of about {eff:.0f}, which limits how much any single holding "
                   f"can dictate the outcome.")
    sec_w = _sector_weights(stats)
    named = [s for s, _ in sec_w if s not in ("Unknown", "Fund / ETF")]
    if len(named) >= 5:
        out.append(f"Exposure spans {len(named)} sectors, so the portfolio is not a "
                   f"single macro bet wearing the clothes of a diversified book.")
    # Everything below is a claim about the RECORD, so none of it may be stated
    # from a handful of sessions. A two-day-old portfolio was being praised for
    # a "0.0% deepest decline most investors can hold through" — technically
    # true, entirely meaningless, and exactly the kind of line that makes a
    # report look automated.
    alpha = m.get("vs S&P 500")
    if not thin and isinstance(alpha, (int, float)) and alpha > 0:
        out.append(f"It is beating the S&P 500 by {alpha:.1f} points on the same "
                   f"contribution schedule — a like-for-like comparison, not a "
                   f"lump-sum one.")
    sharpe = m.get("Sharpe Ratio")
    if not thin and isinstance(sharpe, (int, float)) and sharpe > 1:
        out.append(f"A Sharpe ratio of {sharpe:.2f} indicates the returns earned so "
                   f"far have been adequately paid for in risk terms.")
    dd = m.get("Max Drawdown")
    if not thin and isinstance(dd, (int, float)) and -15 < dd < -0.5:
        out.append(f"The deepest peak-to-trough decline has been {dd:.1f}%, a "
                   f"drawdown most investors can hold through without selling.")
    dy = stats.get("div_yield") or 0
    if dy > 0.025:
        out.append(f"A {_f(dy)} dividend yield provides a return component that does "
                   f"not depend on multiple expansion.")
    beta = stats.get("beta")
    if beta is not None and beta < 0.9:
        out.append(f"A below-market beta of {beta:.2f} means less exposure to broad "
                   f"selloffs than an index position.")
    return out or ["No structural strengths stand out from the current metrics."]


def _concerns(stats, m):
    out = []
    lg = stats.get("largest")
    if lg and lg["w"] > CONCENTRATION_POSITION:
        out.append(f"Single-name concentration: {lg['ticker']} is {_f(lg['w'])} of "
                   f"assets. A 20% move in that one holding shifts the whole "
                   f"portfolio by about {_f(lg['w'] * 0.20)}.")
    if stats["top5"] > 0.60 and stats["n"] > 5:
        out.append(f"The top five positions carry {_f(stats['top5'])} of the "
                   f"portfolio, so most of the outcome is decided by a minority of "
                   f"the holdings.")
    for sec, w in _sector_weights(stats):
        if w > CONCENTRATION_SECTOR and sec not in ("Unknown", "Fund / ETF"):
            out.append(f"{sec} exposure is {_f(w)}, above the 30% level usually "
                       f"treated as a sector concentration. Sector-wide shocks "
                       f"would hit a large share of the book at once.")
    if stats["n"] < 10:
        out.append(f"With {stats['n']} holdings, company-specific risk is a larger "
                   f"share of total risk than it would be in a broader book; the "
                   f"conventional threshold for diversifying away most of it is "
                   f"around 20-30 names.")
    vol = stats.get("vol")
    if vol is not None and vol > 25:
        out.append(f"Annualised volatility of {vol:.1f}% is meaningfully above the "
                   f"S&P 500's long-run ~15%, so wider swings should be expected.")
    dd = m.get("Max Drawdown")
    if isinstance(dd, (int, float)) and dd < -25:
        out.append(f"The portfolio has already drawn down {dd:.1f}% at its worst "
                   f"point, which is the kind of decline that tests conviction.")
    dshare, cshare = _defensive_share(stats)
    if cshare > 0.80:
        out.append(f"{_f(cshare)} of assets sit in cyclical sectors with little "
                   f"defensive ballast, leaving few holdings likely to hold up in a "
                   f"downturn.")
    if stats["n_days"] < 252:
        out.append(f"Only {stats['n_days']} trading days of history exist so far. "
                   f"Risk statistics computed over a window this short describe one "
                   f"market episode rather than a durable characteristic.")
    if not stats.get("profiles_ok"):
        out.append("Sector, valuation and beta data could not be retrieved for these "
                   "holdings, so the exposure and style sections of this report are "
                   "incomplete. This is a data-availability problem, not a finding "
                   "about the portfolio — rebuilding the report usually resolves it.")
    return out or ["No material structural concerns stand out from the current metrics."]


def _diversification(stats):
    hhi, eff, n = stats["hhi"], stats.get("eff_n"), stats["n"]
    # The score is mapped piecewise onto the SAME cut-offs as the band, because
    # (1 - HHI) x 10 rated a 60%-tech, 24%-single-name book at 8.4/10 while the
    # words beside it said "moderately diversified". A number and a label that
    # disagree teach the reader to trust neither.
    if hhi < 0.10:
        band, score = "well diversified", 8.0 + (0.10 - hhi) / 0.10 * 2.0
    elif hhi <= 0.18:
        band, score = "moderately diversified", 5.0 + (0.18 - hhi) / 0.08 * 3.0
    else:
        band, score = "concentrated", max(1.0, 5.0 - (hhi - 0.18) * 12.0)
    score = max(0.0, min(10.0, score))
    txt = (f"On a Herfindahl basis the portfolio scores {hhi:.3f}, which places it in "
           f"the {band} range. Its {n} holdings carry the risk profile of about "
           f"{eff:.0f} equally-weighted positions"
           + (", meaning weight is spread reasonably evenly."
              if hhi <= 0.18 else
              ", meaning a small number of names dominate the risk."))
    return round(score, 1), band, txt


def _sector_commentary(stats):
    sw = _sector_weights(stats)
    named = [(s, w) for s, w in sw if s not in ("Unknown", "Fund / ETF")]
    if not named:
        if not stats.get("profiles_ok"):
            return ("Sector data could not be retrieved for these holdings when this "
                    "report was generated, so exposure could not be assessed. That is "
                    "a temporary data-provider limitation rather than a property of "
                    "the portfolio — building the report again usually fills it in.")
        return ("These holdings are funds rather than individual companies, so they "
                "carry no single sector of their own; look through to each fund's "
                "own holdings to assess exposure.")
    top, tw = named[0]
    txt = f"The largest sector exposure is {top} at {_f(tw)} of assets"
    if len(named) > 1:
        s2, w2 = named[1]
        txt += f", followed by {s2} at {_f(w2)}"
    txt += ". "
    if tw > CONCENTRATION_SECTOR:
        txt += (f"That is above the 30% level at which a sector stops being a tilt "
                f"and starts being the portfolio's dominant risk factor. ")
    dshare, cshare = _defensive_share(stats)
    if dshare or cshare:
        txt += (f"Split by character, roughly {_f(dshare)} sits in defensive sectors "
                f"and {_f(cshare)} in cyclicals, ")
        txt += ("a balance that should moderate drawdowns."
                if dshare > 0.30 else
                "so the portfolio leans on economic expansion to perform.")
    fund_w = sum(w for s, w in sw if s == "Fund / ETF")
    if fund_w > 0.15:
        txt += (f" A further {_f(fund_w)} sits in funds or ETFs, whose look-through "
                f"exposure is broader than these single-name figures show.")
    return txt


def _performance(stats, m):
    """Drivers, best and worst, and the benchmark comparison."""
    contribs = _contributions(stats)
    total_gain = sum(c["gain_usd"] for c in contribs) or 0.0
    lines = []
    tr, alpha = m.get("Total Return"), m.get("vs S&P 500")
    spx = m.get("S&P 500 Return")
    if tr is not None:
        s = f"The portfolio has returned {_pct(tr, sign=True)} on capital invested."
        if isinstance(spx, (int, float)):
            s += (f" An S&P 500 position funded on the same schedule returned "
                  f"{_pct(spx, sign=True)} over the same period")
            if isinstance(alpha, (int, float)):
                s += (f", leaving the portfolio {abs(alpha):.1f} points "
                      f"{'ahead' if alpha >= 0 else 'behind'}.")
            else:
                s += "."
        lines.append(s)
    if contribs and total_gain:
        winners = [c for c in contribs if (c["gain_usd"] or 0) > 0]
        if winners:
            top3 = winners[:3]
            won = sum(c["gain_usd"] for c in top3)
            share = won / total_gain if total_gain else 0
            names = ", ".join(f"{c['ticker']} (${c['gain_usd']:,.0f})" for c in top3)
            if 0 < share <= 1.0:
                tail = (f", which together account for {share:.0%} of the "
                        f"portfolio's total gain.")
            elif share > 1.0:
                # Winners can exceed the NET gain, because losers offset them.
                # Printing "119% of total gain" is arithmetically right and reads
                # as a bug, so say what it actually means instead.
                tail = (f", which between them produced more than the portfolio's "
                        f"entire net gain — losses elsewhere gave part of it back.")
            else:
                tail = "."
            lines.append("Gains are concentrated in " + names + tail)
        losers = [c for c in contribs if (c["gain_usd"] or 0) < 0]
        if losers:
            worst = sorted(losers, key=lambda c: c["gain_usd"])[:3]
            lines.append(
                "Offsetting that, " +
                ", ".join(f"{c['ticker']} (${c['gain_usd']:,.0f})" for c in worst) +
                " have detracted from the result.")
    if not lines:
        lines.append("Not enough history yet to attribute performance.")
    return lines, contribs


def _environments(stats):
    """Where this portfolio should do well, and where it should struggle."""
    beta = stats.get("beta")
    dshare, cshare = _defensive_share(stats)
    style, _ = _style_tilt(stats)
    dy = stats.get("div_yield") or 0
    out_ok, out_bad = [], []

    if beta is not None and beta > 1.1:
        out_ok.append("broad market rallies, where its above-market beta amplifies gains")
        out_bad.append("sharp selloffs, where the same sensitivity works against it")
    elif beta is not None and beta < 0.9:
        out_ok.append("falling or choppy markets, where its below-market beta limits damage")
        out_bad.append("strong momentum-led rallies, where it should lag the index")
    if style == "Growth":
        out_ok.append("falling-rate environments, which raise the present value of "
                      "distant earnings")
        out_bad.append("rising-rate or inflationary periods, which compress the "
                       "multiples growth names depend on")
    elif style == "Value":
        out_ok.append("rising-rate periods, when near-term cash flows are favoured "
                      "over distant ones")
        out_bad.append("speculative rallies, where expensive growth tends to lead")
    elif style == "Income":
        out_ok.append("income-seeking markets and falling equity risk appetite")
        out_bad.append("rising-rate periods, when bond yields compete directly with "
                       "dividend yield")
    if dshare > 0.35:
        out_ok.append("late-cycle slowdowns, given the defensive sector weighting")
    if cshare > 0.70:
        out_bad.append("recessions, given how much of the book is cyclical")
    if dy > 0.03:
        out_ok.append("flat markets, where the dividend does the work")
    return (out_ok or ["conditions broadly similar to the market's"],
            out_bad or ["conditions that disadvantage the market as a whole"])


def _themes(stats):
    """What the portfolio is actually betting on."""
    out = []
    sw = [(s, w) for s, w in _sector_weights(stats)
          if s not in ("Unknown", "Fund / ETF")]
    if sw and sw[0][1] > 0.25:
        out.append(f"{sw[0][0]} leadership — {_f(sw[0][1])} of assets ride on that "
                   f"sector continuing to perform.")
    lg = stats.get("largest")
    if lg and lg["w"] > 0.15:
        # A fund is not a company. Calling a 17% QQQ position "a single-company
        # thesis" is wrong on its face and undermines everything around it.
        if (lg.get("sector") == "Fund / ETF"):
            out.append(f"A core holding in {lg['name']} at {_f(lg['w'])}, which gives "
                       f"the portfolio broad market exposure in a single position.")
        else:
            out.append(f"A concentrated position in {lg['name']} at {_f(lg['w'])}, "
                       f"which functions as a single-company thesis inside the "
                       f"portfolio.")
    g = stats.get("rev_growth")
    if g is not None and g > 0.15:
        out.append(f"Above-average revenue growth ({_f(g)} weighted), so the book is "
                   f"positioned for expansion rather than stability.")
    dy = stats.get("div_yield") or 0
    if dy > 0.03:
        out.append(f"An income stream of {_f(dy)}, which cushions total return when "
                   f"prices stall.")
    beta = stats.get("beta")
    if beta is not None and beta > 1.2:
        out.append(f"A deliberate risk-on stance ({beta:.2f} beta) rather than a "
                   f"capital-preservation posture.")
    fund_w = sum(w for s, w in _sector_weights(stats) if s == "Fund / ETF")
    if fund_w > 0.25:
        out.append(f"A {_f(fund_w)} core of funds/ETFs providing broad market beta "
                   f"around the single-name positions.")
    return out or ["No dominant theme — exposure is spread without a strong tilt."]


def _recommendations(stats, m):
    """Specific, checkable observations. Framed as considerations, not advice."""
    out = []
    lg = stats.get("largest")
    if lg and lg["w"] > 0.25:
        out.append(f"Consider whether {lg['ticker']} at {_f(lg['w'])} reflects "
                   f"conviction or simply drift from appreciation. Trimming to "
                   f"20% would release about "
                   f"${(lg['w'] - 0.20) * stats['total_value']:,.0f} to redeploy.")
    if stats["n"] < 12:
        out.append(f"The portfolio holds {stats['n']} positions. Research on "
                   f"diversification generally puts the point of diminishing "
                   f"company-specific risk reduction near 20-30 names; adding "
                   f"uncorrelated exposure would reduce single-stock risk.")
    sw = _sector_weights(stats)
    over = [(s, w) for s, w in sw if w > CONCENTRATION_SECTOR
            and s not in ("Unknown", "Fund / ETF")]
    for s, w in over:
        out.append(f"{s} is {_f(w)} of assets. Reducing toward 25-30% would lower "
                   f"the portfolio's dependence on one sector's cycle.")
    present = {s for s, _ in sw}
    missing = [s for s in ("Healthcare", "Consumer Defensive", "Utilities",
                           "Financial Services", "Energy")
               if s not in present]
    if missing and stats["n"] >= 5:
        out.append("No exposure to " + ", ".join(missing[:3]) +
                   ". Adding one or more would broaden the portfolio's response to "
                   "different phases of the cycle.")
    dshare, cshare = _defensive_share(stats)
    if cshare > 0.75 and dshare < 0.15:
        out.append("Defensive sectors are largely absent. A position in staples, "
                   "healthcare or utilities would provide ballast in a downturn.")
    vol = stats.get("vol")
    if vol is not None and vol > 30:
        out.append(f"At {vol:.1f}% annualised volatility, position sizing matters "
                   f"more than usual — consider whether the largest holdings are "
                   f"sized for the swings they actually produce.")
    dd = m.get("Max Drawdown")
    if isinstance(dd, (int, float)) and dd < -20:
        out.append(f"Having already seen a {dd:.1f}% drawdown, it is worth deciding "
                   f"in advance what action, if any, a repeat would trigger.")
    if stats["n_days"] < 252:
        out.append("Revisit these figures after a full year of tracking; the current "
                   "window is too short to separate skill from market conditions.")
    return out or ["No specific rebalancing considerations arise from the current "
                   "structure."]


def build_narrative(name, tracked, stats):
    """Everything the reports need to write about this portfolio.

    `stats` is portfolio_excel._derive_portfolio_stats(tracked, profiles).
    """
    m = tracked.get("metrics", {}) or {}
    style_lbl, style_txt = _style_tilt(stats)
    posture_lbl, posture_txt = _posture(stats)
    div_score, div_band, div_txt = _diversification(stats)
    perf_lines, contribs = _performance(stats, m)
    env_ok, env_bad = _environments(stats)

    winners = [c for c in contribs if (c["gain_usd"] or 0) > 0][:5]
    losers = sorted([c for c in contribs if (c["gain_usd"] or 0) < 0],
                    key=lambda c: c["gain_usd"])[:5]

    return {
        "name": name,
        "objective": _objective(stats),
        "assessment": _assessment(stats, m),
        "strengths": _strengths(stats, m),
        "concerns": _concerns(stats, m),
        "diversification_score": div_score,
        "diversification_band": div_band,
        "diversification_text": div_txt,
        "sector_commentary": _sector_commentary(stats),
        "style_label": style_lbl,
        "style_text": style_txt,
        "posture_label": posture_lbl,
        "posture_text": posture_txt,
        "performance_lines": perf_lines,
        "contributions": contribs,
        "winners": winners,
        "losers": losers,
        "themes": _themes(stats),
        "environments_favourable": env_ok,
        "environments_adverse": env_bad,
        "recommendations": _recommendations(stats, m),
    }
